#!/usr/bin/env bash

OPTIND=1
DOCKER_ARGS=""
DOCKER_ARGS_OPT=""

reset_options="--no-cache"
build_options="--force-rm --build-arg UID=$(id -u) --build-arg GID=$(id -g)"

source vars.cfg
echo "Building ${image_name}"

docker build $BUILD_ARGS $DOCKER_ARGS_OPT --tag $image_name "./"
